Repository openmsa/Workflows, pull requests merged in 2020-10, with the labels that each got.

#106 Update utils me var mngt
  Utils/Manage_Device_Conf_Variables/.meta_Delete_Variable_Delete.php
  Utils/Manage_Device_Conf_Variables/.meta_Init_Select_ME.php
  Utils/Manage_Device_Conf_Variables/Delete_Variable_Delete.php
  Utils/Manage_Device_Conf_Variables/Init_Select_ME.php
Labels: enhancement

#114 VRF based topology has been added
  Topology/.meta_Topology.xml
  Topology/Common/Topology_common.php
  Topology/Process_Create_View/Tasks/.meta_Task_Create.php
  Topology/Process_Create_View/Tasks/Task_Create.php
  Topology/Process_Update_View/Tasks/.meta_Task_Update.php
  Topology/Process_Update_View/Tasks/Task_Update.php
  Topology/Topology.xml
  Topology/Topology_Types/VRF.php
Labels: enhancement

#121 AWS Public Cloud WF: fix path to autoload.php
  Public_Cloud/AWS/Instance_Management/Process_CREATE/Tasks/Task_Create_KeyPair.php
  Public_Cloud/AWS/Instance_Management/Process_CREATE/Tasks/Task_Create_Network_interfaces.php
  Public_Cloud/AWS/Instance_Management/Process_CREATE/Tasks/Task_Create_VM.php
  Public_Cloud/AWS/Instance_Management/Process_CREATE/Tasks/Task_Wait_for_device_Ping.php
  Public_Cloud/AWS/Instance_Management/Process_CREATE/Tasks/Task_attach_network_interfaces_to_VNFC_instance.php
  Public_Cloud/AWS/Instance_Management/Process_CREATE/Tasks/Task_wait_for_instance.php
  Public_Cloud/AWS/Instance_Management/Process_Create_net_iface/Tasks/Task_Create_network_interfaces.php
  Public_Cloud/AWS/Instance_Management/Process_Delete/Tasks/Task_Delete_VM_on_AWS.php
  Public_Cloud/AWS/Instance_Management/Process_New_service/Tasks/Task_Synchronization_to_AWS_cloud.php
  Public_Cloud/AWS/Instance_Management/Process_Reboot_VNFC/Tasks/Task_Reboot_VNFC.php
  Public_Cloud/AWS/Instance_Management/Process_Restart_VNFC/Tasks/Task_Restart_VNFC.php
  Public_Cloud/AWS/Instance_Management/Process_Start_VNFC/Tasks/Task_start_vnfc.php
  Public_Cloud/AWS/Instance_Management/Process_Stop_VNFC/Tasks/Task_stop_vnfc.php
  Public_Cloud/AWS/Instance_Management/Process_Terminate_VNFC/Tasks/Task_Delete_VM_on_AWS.php
  Public_Cloud/AWS/Instance_Management/Process_Terminate_service/Tasks/Task_Remove_network_interfaces.php
  Public_Cloud/AWS/Instance_Management/Process_Terminate_service/Tasks/Task_Wait.php
Labels: bug

#127 MEC Workload Placement
  MEC/k8s_metrics_wf_01/.meta_CREATE_NAMESPACE_call_k8s_api.py
  MEC/k8s_metrics_wf_01/.meta_CREATE_NAMESPACE_get_ips_and_ids.py
  MEC/k8s_metrics_wf_01/.meta_CREATE_NAMESPACE_prepare_data.py
  MEC/k8s_metrics_wf_01/.meta_CREATE_NAMESPACE_prepare_data_for_microservice.py
  MEC/k8s_metrics_wf_01/.meta_CREATE_NAMESPACE_prepare_microservice_data.py
  MEC/k8s_metrics_wf_01/.meta_DELETE_WF_INSTANCE_delete.py
  MEC/k8s_metrics_wf_01/.meta_k8s_metrics_wf_01.xml
  MEC/k8s_metrics_wf_01/CREATE_NAMESPACE_call_k8s_api.py
  MEC/k8s_metrics_wf_01/CREATE_NAMESPACE_get_ips_and_ids.py
  MEC/k8s_metrics_wf_01/CREATE_NAMESPACE_prepare_data.py
  MEC/k8s_metrics_wf_01/CREATE_NAMESPACE_prepare_data_for_microservice.py
  MEC/k8s_metrics_wf_01/CREATE_NAMESPACE_prepare_microservice_data.py
  MEC/k8s_metrics_wf_01/DELETE_WF_INSTANCE_delete.py
  MEC/k8s_metrics_wf_01/k8s_metrics_wf_01.xml
  MEC/k8s_metrics_wf_02/.meta_CLEANUP_DEPLOYMENTS_remove_pods_and_apps.py
  MEC/k8s_metrics_wf_02/.meta_CLEANUP_remove_pods_and_apps.py
  MEC/k8s_metrics_wf_02/.meta_DEPLOY_MEC_APP_collect_metrics_from_pods.py
  MEC/k8s_metrics_wf_02/.meta_DEPLOY_MEC_APP_deploy_user_app.py
  MEC/k8s_metrics_wf_02/.meta_DEPLOY_PROBATION_CONSTRUCT_PROBAITON.py
  MEC/k8s_metrics_wf_02/.meta_DEPLOY_PROBATION_construct_probation_network.py
  MEC/k8s_metrics_wf_02/.meta_DEPLOY_PROBATION_deploy_pods.py
  MEC/k8s_metrics_wf_02/.meta_EXIT_remove_workflow_instance.py
  MEC/k8s_metrics_wf_02/.meta_INITIALIZE_collect_metrics_from_pods.py
  MEC/k8s_metrics_wf_02/.meta_INITIALIZE_construct_data.py
  MEC/k8s_metrics_wf_02/.meta_INITIALIZE_construct_probation_packet.py
  MEC/k8s_metrics_wf_02/.meta_INITIALIZE_create_pods.py
  MEC/k8s_metrics_wf_02/.meta_INITIALIZE_prepare_user_input_data.py
  MEC/k8s_metrics_wf_02/.meta_INITIALIZE_retrieve_user_input_data.py
  MEC/k8s_metrics_wf_02/.meta_k8s_metrics_wf_02.xml
  MEC/k8s_metrics_wf_02/CLEANUP_DEPLOYMENTS_remove_pods_and_apps.py
  MEC/k8s_metrics_wf_02/CLEANUP_remove_pods_and_apps.py
  MEC/k8s_metrics_wf_02/DEPLOY_MEC_APP_collect_metrics_from_pods.py
  MEC/k8s_metrics_wf_02/DEPLOY_MEC_APP_deploy_user_app.py
  MEC/k8s_metrics_wf_02/DEPLOY_PROBATION_CONSTRUCT_PROBAITON.py
  MEC/k8s_metrics_wf_02/DEPLOY_PROBATION_construct_probation_network.py
  MEC/k8s_metrics_wf_02/DEPLOY_PROBATION_deploy_pods.py
  MEC/k8s_metrics_wf_02/EXIT_remove_workflow_instance.py
  MEC/k8s_metrics_wf_02/INITIALIZE_collect_metrics_from_pods.py
  MEC/k8s_metrics_wf_02/INITIALIZE_construct_data.py
  MEC/k8s_metrics_wf_02/INITIALIZE_construct_probation_packet.py
  MEC/k8s_metrics_wf_02/INITIALIZE_create_pods.py
  MEC/k8s_metrics_wf_02/INITIALIZE_prepare_user_input_data.py
  MEC/k8s_metrics_wf_02/INITIALIZE_retrieve_user_input_data.py
  MEC/k8s_metrics_wf_02/k8s_metrics_wf_02.xml
Labels: help wanted

#130 Minor Changes
  General_Network_Service_Automation/.meta_General_network_service_automation.xml
  General_Network_Service_Automation/.meta_New_CE_Create_CE_device.py
  General_Network_Service_Automation/General_network_service_automation.xml
  General_Network_Service_Automation/New_CE_Create_CE_device.py
  General_Network_Service_Automation/New_L3VPN_Prepare_IP_address_schema.py
Labels: enhancement
